# -*- coding: utf-8 -*-
"""python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bMDuuBtqjqnjgEw2CPiD2U_4B2yhGmtY
"""

text = input("Enter your word: ")
vowels = ['a','e','i','o','u']
x= []
for i in text.lower():
  if i in vowels:
    x.append(i)
print(x)

list = [1,1,3,4,4,4,6,7,8,8,8]

if i in list

list = [1,1,3,4,4,4,6,7,8,8,8]
d = {}
for i in list:
  if i in d:
    d[i] += 1

  else:
    d[i] = 1

print(d)

str = "betty bought some butter but the butter was bitter ,so betty bought some more butter"

x = str.split(' ')
d = set(x)
print(f"no of unique words = {len(d)}")



while True:
  z = input("do you want to add data?(yes/no): ")
  if z.lower() == 'yes':
    x = input("Enter your name : ")
    y = input ("Enter your age : ")
    z = f'My name is {x} and i am {y} years old'
    print(z.format(x,y))

  elif z.lower() == 'no':
    break

  else:
    print('type yes or no')

import math

a = int(input("Enter first number : "))
b = int(input("Enter second number : "))
c = int(input("Enter third number : "))

z = (a+b+c)/3

print("Here is the average : ", z)

length = int(input("Enter the length of cuboid : "))
breadth = int(input("Enter the breadth of cuboid : "))
height = int(input("Enter the height of cuboid : "))

volume = length * breadth * height

print("volume of cuboid : ", volume)

x = [10,20,30,10,40,20,40,50,60,30]

dict = {}
for i in x:
  if i in dict:
    dict[i] += 1

  else:
    dict[i] = 1

print(dict)

n = int(input('enter any natural number'))
z = (n *(n + 1))/2
print(z)

i= 1
while i < 6:
  print(i * '*')
  i += 1

x = int(input("enter a num"))
num = 1
for i in range(1,x+1):
  num *= i
print(num)



x = 5
for i in range(0, x):
	for y in range(0, i+1):
		print("*", end=" ")
	print()

import pandas as pd

df = pd.read_csv("monthly-beer-production-in-austr.csv")
df.describe

import matplotlib.pyplot as plt
import numpy as np

x = np.array([2,4])
y = np.array([30,60])

plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([20,45,5,15,5,10])

plt.pie(x)
plt.show()

plt.hist(x)
plt.show()

"""df.describe

"""